In [12]:
from sklearn.model_selection import GridSearchCV
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from scikeras.wrappers import KerasClassifier
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation
from tensorflow.keras.callbacks import EarlyStopping
# from keras.utils.vis_utils import plot_model
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier 
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn import tree
# from sklearn.externals.six import StringIO  
from sklearn.metrics import confusion_matrix
from matplotlib import pyplot as pyplot
from sklearn.metrics import roc_auc_score, roc_curve
# from sklearn.metrics import plot_confusion_matrix
from warnings import simplefilter
import time
start = time.time()

In [13]:
#with two dataset splitted
dftrain = pd.read_csv("train70_reduced.csv") 
dftest = pd.read_csv("test30_reduced.csv")
simplefilter(action='ignore', category=FutureWarning)
seed = 7

In [14]:
'''
#one dataset to be splitted
df = pd.read_csv("mqttdataset.csv") 
seed = 7
class_names = df.target.unique()
df=df.astype('category')
cat_columns = df.select_dtypes(['category']).columns
df[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)

x_columns = df.columns.drop('target')
x = df[x_columns].values
y = df['target']

print("Ready to generate train and test datasets")
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=seed)
print("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))
'''

'\n#one dataset to be splitted\ndf = pd.read_csv("mqttdataset.csv") \nseed = 7\nclass_names = df.target.unique()\ndf=df.astype(\'category\')\ncat_columns = df.select_dtypes([\'category\']).columns\ndf[cat_columns] = df[cat_columns].apply(lambda x: x.cat.codes)\n\nx_columns = df.columns.drop(\'target\')\nx = df[x_columns].values\ny = df[\'target\']\n\nprint("Ready to generate train and test datasets")\nx_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=seed)\nprint("x_train, y_train, x_test, y_test" + str(x_train.shape) + "" +str(y_train.shape) + "" +str(x_test.shape) + "" +str(y_test.shape))\n'

In [15]:
#train
#print(dftrain.loc[dftrain['target'] == 'legitimate'])
class_names = dftrain.target.unique()
dftrain=dftrain.astype('category')
cat_columns = dftrain.select_dtypes(['category']).columns
dftrain[cat_columns] = dftrain[cat_columns].apply(lambda x: x.cat.codes)
#print(dftrain.loc[125, 'target'])
x_columns = dftrain.columns.drop('target')
x_train = dftrain[x_columns].values
y_train = dftrain['target']

In [16]:
#test
class_names = dftest.target.unique()
dftest=dftest.astype('category')
cat_columns = dftest.select_dtypes(['category']).columns
dftest[cat_columns] = dftest[cat_columns].apply(lambda x: x.cat.codes)
x_columns = dftest.columns.drop('target')
x_test = dftest[x_columns].values
y_test = dftest['target']

In [17]:
print("Ready to generate train and test datasets")

Ready to generate train and test datasets


In [18]:
#Neural network
print("Starting Random forest")
model = Sequential()
model.add(Dense(50, input_dim=x_train.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(30, input_dim=x_train.shape[1], kernel_initializer='normal', activation='relu'))
model.add(Dense(20, kernel_initializer='normal'))
model.add(Dense(6,activation='softmax'))
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
monitor = EarlyStopping(monitor='val_loss', min_delta=1e-3, patience=5, verbose=1, mode='auto')
history = model.fit(x_train,y_train,validation_data=(x_test,y_test),callbacks=[monitor],verbose=2,epochs=200,batch_size=1000) 
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_nn = model.predict(x_test)
y_pred_nn = np.argmax(y_pred_nn,axis=1)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

Starting Random forest
Epoch 1/200
232/232 - 1s - loss: 0.9689 - accuracy: 0.7617 - val_loss: 0.5873 - val_accuracy: 0.7821 - 1s/epoch - 6ms/step
Epoch 2/200
232/232 - 1s - loss: 0.5234 - accuracy: 0.7892 - val_loss: 0.4763 - val_accuracy: 0.8318 - 508ms/epoch - 2ms/step
Epoch 3/200
232/232 - 1s - loss: 0.4119 - accuracy: 0.8578 - val_loss: 0.4219 - val_accuracy: 0.8510 - 555ms/epoch - 2ms/step
Epoch 4/200
232/232 - 1s - loss: 0.3713 - accuracy: 0.8785 - val_loss: 0.4014 - val_accuracy: 0.8601 - 672ms/epoch - 3ms/step
Epoch 5/200
232/232 - 0s - loss: 0.3326 - accuracy: 0.8873 - val_loss: 0.4349 - val_accuracy: 0.8537 - 492ms/epoch - 2ms/step
Epoch 6/200
232/232 - 1s - loss: 0.3130 - accuracy: 0.8925 - val_loss: 0.4366 - val_accuracy: 0.8436 - 536ms/epoch - 2ms/step
Epoch 7/200
232/232 - 1s - loss: 0.2691 - accuracy: 0.9089 - val_loss: 0.4197 - val_accuracy: 0.8520 - 566ms/epoch - 2ms/step
Epoch 8/200
232/232 - 1s - loss: 0.2496 - accuracy: 0.9159 - val_loss: 0.3835 - val_accuracy: 0.85

In [19]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                1700      
                                                                 
 dense_1 (Dense)             (None, 30)                1530      
                                                                 
 dense_2 (Dense)             (None, 20)                620       
                                                                 
 dense_3 (Dense)             (None, 6)                 126       
                                                                 
Total params: 3976 (15.53 KB)
Trainable params: 3976 (15.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [20]:
#RandomForest
print("Starting Random forest")
classifier = RandomForestClassifier(verbose=2,random_state=seed)
classifier.fit(x_train, y_train)
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_random = classifier.predict(x_test)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

Starting Random forest
building tree 1 of 100
building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
bu

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    3.1s


building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84

[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    0.3s


Test time: 0.6898400783538818


In [21]:
#Create Naive Bayes Classifier
print("Starting Naive Bayes")
gnb = GaussianNB()
gnb.fit(x_train, y_train)
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_nb = gnb.predict(x_test)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

Starting Naive Bayes
Training time: 23.89258909225464
Test time: 0.07552599906921387


In [22]:
#Decision tree
print("Starting Decision tree")
clf = DecisionTreeClassifier()
clf = clf.fit(x_train,y_train)
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_dt = clf.predict(x_test)
y_pred_dt_roc = clf.predict_proba(x_test)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

Starting Decision tree
Training time: 24.372718572616577
Test time: 0.015669584274291992


In [23]:
#Multi layer perceptron
print("Starting Multi layer perceptron")
model = MLPClassifier( max_iter=130, batch_size=1000, alpha=1e-4, activation = 'relu',solver='adam', verbose=10, tol=1e-4, random_state=seed)
model.fit(x_train, y_train)
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_mlp = model.predict(x_test)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

Starting Multi layer perceptron
Iteration 1, loss = 2.97328830
Iteration 2, loss = 0.51288083
Iteration 3, loss = 0.58269938
Iteration 4, loss = 0.61906464
Iteration 5, loss = 0.49762046
Iteration 6, loss = 0.64565707
Iteration 7, loss = 0.32041043
Iteration 8, loss = 0.40561145
Iteration 9, loss = 0.77652752
Iteration 10, loss = 0.34245641
Iteration 11, loss = 0.39090587
Iteration 12, loss = 0.34794928
Iteration 13, loss = 0.60804647
Iteration 14, loss = 0.30455291
Iteration 15, loss = 0.43960638
Iteration 16, loss = 0.47540445
Iteration 17, loss = 0.54364130
Iteration 18, loss = 0.38249815
Iteration 19, loss = 0.30610474
Iteration 20, loss = 0.33905626
Iteration 21, loss = 0.67541611
Iteration 22, loss = 0.32885779
Iteration 23, loss = 0.31161025
Iteration 24, loss = 0.36841462
Iteration 25, loss = 0.30486415
Training loss did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
Training time: 85.94992470741272
Test time: 0.42185235023498535


In [24]:
#Gradient boost
print("Starting Gradient boost")
model = GradientBoostingClassifier(n_estimators=20, random_state=seed,verbose=2)
model.fit(x_train, y_train)
end = time.time()
diff=end-start
print("Training time: " + str(diff))
starttest = time.time()
y_pred_gradient = model.predict(x_test)
endtest =time.time()
difftest = endtest-starttest
print("Test time: " + str(difftest))

Starting Gradient boost
      Iter       Train Loss   Remaining Time 
         1           0.8918           21.91s
         2           0.7674           20.90s
         3           0.6795           19.94s
         4           0.6010           18.93s
         5           0.5408           17.71s
         6           0.4943           16.55s
         7           0.4595           15.37s
         8           0.4254           14.15s
         9           0.3983           12.96s
        10           0.3768           11.77s
        11           0.3539           10.57s
        12           0.3375            9.37s
        13           0.3203            8.19s
        14           0.3080            7.02s
        15           0.2939            5.84s
        16           0.2834            4.67s
        17           0.2752            3.49s
        18           0.2665            2.33s
        19           0.2575            1.16s
        20           0.2496            0.00s
Training time: 109.68870043754

In [25]:
print("Decision Tree, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_dt)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_dt,average='weighted')))
matrixdt = confusion_matrix(y_test,y_pred_dt)
print(matrixdt)

Decision Tree, accuracy: 0.9031322388961628 F1 score:0.9009088402539802
[[ 3313   571     0     7   460     0]
 [  212 35556     0  3250    59     0]
 [    1     4    90    88     1     0]
 [   19  3144     0 46468     8     0]
 [  992   331    13   456  1486     0]
 [    0     0     0     0     2  2759]]


In [26]:
print("Naive Bayes, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_nb)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_nb,average='weighted')))
matrixnv = confusion_matrix(y_test,y_pred_nb)
print(matrixnv)

Naive Bayes, accuracy: 0.670863128210293 F1 score:0.7581608917548786
[[ 4290    38     8     5    10     0]
 [11198 27866     0    13     0     0]
 [   93     0    89     2     0     0]
 [18473     0     0 31166     0     0]
 [ 2676    94    36    34   438     0]
 [    0     0     0     0     0  2761]]


In [27]:
print("Neural network, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_nn)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_nn,average='weighted')))
matrixnn = confusion_matrix(y_test,y_pred_nn)
print(matrixnn)

Neural network, accuracy: 0.900916507201128 F1 score:0.8983518885415201
[[ 3764   466     5    17    99     0]
 [  252 34888     0  3858    79     0]
 [    2    20    69    89     4     0]
 [   49  2768     0 46637   185     0]
 [ 1359   324     4   258  1333     0]
 [    0     0     0     0     0  2761]]


In [28]:
print("MultiLayerPerceptron, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_mlp)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_mlp,average='weighted')))
matrixml = confusion_matrix(y_test,y_pred_mlp)
print(matrixml)
print("Random Forest, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_random)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_random,average='weighted')))
matrixrf = confusion_matrix(y_test,y_pred_random)
print(matrixrf)
print("GradienBoost, accuracy: " + str(metrics.accuracy_score(y_test, y_pred_gradient)) + " F1 score:" + str(metrics.f1_score(y_test, y_pred_gradient,average='weighted')))
matrixgb = confusion_matrix(y_test,y_pred_gradient)
print(matrixgb)

MultiLayerPerceptron, accuracy: 0.8750125893846309 F1 score:0.8747983763842849
[[ 2802  1012     3   109   425     0]
 [  210 35077     0  3788     2     0]
 [    2     4    66    88    24     0]
 [   49  3180     0 44821  1587     2]
 [  948   622     4   337  1366     1]
 [    9     3     0     0     1  2748]]
Random Forest, accuracy: 0.9029308087420687 F1 score:0.9009131314572056
[[ 3227   572     0     7   545     0]
 [  206 35554     0  3250    67     0]
 [    1     4    89    89     1     0]
 [   19  3144     0 46468     8     0]
 [  951   317     0   457  1553     0]
 [    0     0     0     0     0  2761]]
GradienBoost, accuracy: 0.7931513747608017 F1 score:0.8268049294767623
[[ 3084   506   497   261     3     0]
 [  296 25185  9666  3930     0     0]
 [    2     3     1   178     0     0]
 [   49  2710     0 46880     0     0]
 [  991   362   327   642   956     0]
 [    0     0   115     0     0  2646]]
