In [1]:
import numpy as np

index = np.load("./best_defense_indices.npy")

In [18]:
for i in index:
    unique_values, counts = np.unique(i, return_counts=True)
    print(unique_values,counts)

[ 1  2  3  4  5  6  7  8  9 10] [105856    125    300     94    154   1518     12    174    566   5172]
[ 1  2  3  4  5  6  8  9 10] [106195     51   3260    438    230   2273    214    833    477]
[ 1  2  3  4  5  6  8  9 10] [16662    73   665    36  1901 94414    52    19   149]
[ 1  2  3  4  5  6  8  9 10] [17424    47   725    73  1163 94299    43    28   169]
[ 1  2  3  4  5  6  7  8  9 10] [105905    120    297     94    147   1518      8    184    562   5136]
[ 1  2  3  4  5  6  7  8  9 10] [107544     31   2774    313    187   1905      4    265    523    425]
[ 1  2  3  4  5  6  7  8  9 10] [99740    10   531   465   432 12358    33   270    11   121]
[ 1  2  3  4  5  6  7  8  9 10] [15783    16   235   307   614 96584    36   327     5    64]
[ 1  2  3  4  5  6  7  8  9 10] [105856    125    300     94    154   1518     12    174    566   5172]
[ 1  2  3  4  5  6  8  9 10] [106195     51   3260    438    230   2273    214    833    477]
[ 1  2  3  4  5  6  8  9 10] [16662   